package dato;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACTO".
 */
public class Contacto {

    private Long id;
    private String nombre;
    private String foto;
    private String regId;
    private String telefono;

    public Contacto() {
    }

    public Contacto(Long id) {
        this.id = id;
    }

    public Contacto(Long id, String nombre, String foto, String regId, String telefono) {
        this.id = id;
        this.nombre = nombre;
        this.foto = foto;
        this.regId = regId;
        this.telefono = telefono;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public String getRegId() {
        return regId;
    }

    public void setRegId(String regId) {
        this.regId = regId;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

}
