package dato;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MENSAJE".
 */
public class Mensaje {

    private Long id;
    private String texto;
    private String fecha;
    private String hora;
    private Boolean tipo;
    private Long idContacto;
    private Long idGrupo;

    public Mensaje() {
    }

    public Mensaje(Long id) {
        this.id = id;
    }

    public Mensaje(Long id, String texto, String fecha, String hora, Boolean tipo, Long idContacto, Long idGrupo) {
        this.id = id;
        this.texto = texto;
        this.fecha = fecha;
        this.hora = hora;
        this.tipo = tipo;
        this.idContacto = idContacto;
        this.idGrupo = idGrupo;
    }

    public Mensaje(String texto, String fecha, String hora, Boolean tipo, Long idContacto, Long idGrupo) {
        this.texto = texto;
        this.fecha = fecha;
        this.hora = hora;
        this.tipo = tipo;
        this.idContacto = idContacto;
        this.idGrupo = idGrupo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTexto() {
        return texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }

    public Boolean getTipo() {
        return tipo;
    }

    public void setTipo(Boolean tipo) {
        this.tipo = tipo;
    }

    public Long getIdContacto() {
        return idContacto;
    }

    public void setIdContacto(Long idContacto) {
        this.idContacto = idContacto;
    }

    public Long getIdGrupo() {
        return idGrupo;
    }

    public void setIdGrupo(Long idGrupo) {
        this.idGrupo = idGrupo;
    }

}
