package dato;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USUARIO".
 */
public class Usuario {

    private Long id;
    private String nombre;
    private String foto;
    private String regId;
    private Long idMoodle;

    public Usuario() {
    }

    public Usuario(Long id) {
        this.id = id;
    }

    public Usuario(Long id, String nombre, String foto, String regId, Long idMoodle) {
        this.id = id;
        this.nombre = nombre;
        this.foto = foto;
        this.regId = regId;
        this.idMoodle = idMoodle;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public String getRegId() {
        return regId;
    }

    public void setRegId(String regId) {
        this.regId = regId;
    }

    public Long getIdMoodle() {
        return idMoodle;
    }

    public void setIdMoodle(Long idMoodle) {
        this.idMoodle = idMoodle;
    }
}
